import Head from "next/head";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mahdo blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <section>
          <h2 className="articles__title">Articles</h2>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
